package com.example.ui

object LanguageManager {
    enum class Language(val code: String, val displayName: String) {
        ENGLISH("en", "English"),
        HINDI("hi", "हिन्दी (Hindi)"),
        NEPALI("ne", "नेपाली (Nepali)"),
        JAPANESE("ja", "日本語 (Japanese)"),
        SPANISH("es", "Español (Spanish)"),
        GERMAN("de", "Deutsch (German)"),
        FRENCH("fr", "Français (French)")
    }

    private val translations = mapOf(
        Language.ENGLISH to mapOf(
            "app_title" to "ReaderMe",
            "library" to "Library",
            "player" to "Player",
            "stats" to "Stats",
            "memos" to "Memos",
            "customise" to "Customise Theme",
            "settings" to "Settings",
            "hamburger_menu" to "Menu",
            "made_with_love" to "Made with ♥ by Editingcells",
            "import_safe" to "Import Content Safely",
            "cancel" to "Cancel",
            "save_read" to "Save & Read",
            "theme" to "Theme Palette",
            "dark_mode" to "Dark Mode",
            "font_size" to "Font Size Ratio",
            "select_lang" to "Languages",
            "developer_credit" to "Developer Credits",
            "no_books" to "No books match current search filters.",
            "import_now" to "Import Now",
            "write_note" to "Write a Note / Paste Text",
            "read_clip" to "Read from Clipboard",
            "import_files" to "Import Document Files (TXT, PDF, EPUB)",
            "devices_storage" to "Device Storage & SD Card Scan",
            "search_desc" to "Search inside books, notes, offline files...",
            "audiobook" to "Audiobook Theater",
            "reading_active" to "Reading Active",
            "play_speech" to "Play Speech",
            "sentence" to "Sentence",
            "voice_style" to "Voice Preset",
            "speed" to "Speech Speed",
            "pitch" to "Speech Pitch",
            "timer" to "Sleep Timer",
            "hours" to "hours",
            "minutes" to "minutes",
            "import_photo" to "Custom Cover Image",
            "photo_prompt" to "Paste Cover Photo URL / Unsplash Keyword",
            "read_without_audio" to "Read Without Audio (Simple Mode)",
            "add_audio_later" to "You are reading offline without voice playback.",
            "enable_audio" to "Enable Audio Playback Later",
            "validation_too_short" to "Content is empty or too short! Must be at least 15 characters.",
            "validation_title_empty" to "Title cannot be empty!",
            "scanned_title" to "Scanned Device Ebooks",
            "choose_preset_cover" to "Select Pastel Cover Design",
            "custom_ui_adjustments" to "Interface Styles",
            "close" to "Close",
            "play" to "Play",
            "pause" to "Pause",
            "stop" to "Stop",
            "previous" to "Previous",
            "next" to "Next",
            "text_preview" to "ReaderMe Typography Preview Size",
            "sim_file_alert" to "Only scanned documents with text layout are supported!"
        ),
        Language.HINDI to mapOf(
            "app_title" to "रीडरमी",
            "library" to "पुस्तकालय",
            "player" to "प्लेयर",
            "stats" to "आँकड़े",
            "memos" to "मेमो",
            "customise" to "थीम अनुकूलित",
            "settings" to "सेटिंग्स",
            "hamburger_menu" to "मेन्यू",
            "made_with_love" to "Editingcells द्वारा ♥ से निर्मित",
            "import_safe" to "सामग्री सुरक्षित आयात करें",
            "cancel" to "रद्द करें",
            "save_read" to "सहेजें और पढ़ें",
            "theme" to "थीम पैलेट",
            "dark_mode" to "डार्क मोड",
            "font_size" to "फ़ॉन्ट अनुपात",
            "select_lang" to "भाषाएं",
            "developer_credit" to "डेवलपर श्रेय",
            "no_books" to "कोई पुस्तकें खोज फ़िल्टर से मेल नहीं खातीं।",
            "import_now" to "अभी आयात करें",
            "write_note" to "एक नोट लिखें / संपादन पाठ",
            "read_clip" to "क्लिपबोर्ड से पढ़ें",
            "import_files" to "फ़ाइलें आयात करें (TXT, PDF, EPUB)",
            "devices_storage" to "डिवाइस संग्रहण और एसडी कार्ड",
            "search_desc" to "पुस्तकों, नोटों, ऑफ़लाइन फ़ाइलों के भीतर खोजें...",
            "audiobook" to "ऑडियोबुक थिएटर",
            "reading_active" to "पठन सक्रिय",
            "play_speech" to "भाषण चलाएं",
            "sentence" to "वाक्य",
            "voice_style" to "आवाज शैली",
            "speed" to "गति",
            "pitch" to "पिच",
            "timer" to "स्लीप टाइमर",
            "hours" to "घंटे",
            "minutes" to "मिनट",
            "import_photo" to "कस्टम कवर फोटो",
            "photo_prompt" to "कवर थंबनेल छवि का URL दर्ज करें",
            "read_without_audio" to "ऑडियो के बिना पढ़ें (सरल मोड)",
            "add_audio_later" to "आप वॉयस प्लेबैक के बिना ऑफ़लाइन पढ़ रहे हैं।",
            "enable_audio" to "बाद में ऑडियो सक्षम करें",
            "validation_too_short" to "सामग्री खाली या बहुत छोटी है! कम से कम 15 अक्षर होने चाहिए।",
            "validation_title_empty" to "शीर्षक खाली नहीं हो सकता!",
            "scanned_title" to "स्कैन किए गए डिवाइस ई-बुक्स",
            "choose_preset_cover" to "पेस्टल कवर डिज़ाइन चुनें",
            "custom_ui_adjustments" to "इंटरफ़ेस शैलियाँ",
            "close" to "बंद करें",
            "play" to "चलाएं",
            "pause" to "रोकें",
            "stop" to "बंद करें",
            "previous" to "पिछला",
            "next" to "अगला",
            "text_preview" to "रीडरमी फ़ॉन्ट पूर्वावलोकन",
            "sim_file_alert" to "केवल पाठ लेआउट वाले दस्तावेज़ समर्थित हैं!"
        ),
        Language.NEPALI to mapOf(
            "app_title" to "रीडरमी",
            "library" to "पुस्तकालय",
            "player" to "प्लेयर",
            "stats" to "तथ्याङ्क",
            "memos" to "मेमोहरू",
            "customise" to "थिम अनुकूलन",
            "settings" to "सेटिङ्हरू",
            "hamburger_menu" to "मेनु",
            "made_with_love" to "Editingcells द्वारा ♥ सँग बनाइएको",
            "import_safe" to "सामग्री सुरक्षित आयात गर्नुहोस्",
            "cancel" to "रद्द गर्नुहोस्",
            "save_read" to "सचोट र पढ्नुहोस्",
            "theme" to "थिम प्यालेट",
            "dark_mode" to "डार्क मोड",
            "font_size" to "अक्षर अनुपात",
            "select_lang" to "भाषाहरू थप्नुहोस्",
            "developer_credit" to "डेवलपर क्रेडिट",
            "no_books" to "कुनै पनि पुस्तकहरू फेला परेनन्।",
            "import_now" to "अहिले आयात गर्नुहोस्",
            "write_note" to "नोट लेख्नुहोस् / टाँसिएको पाठ",
            "read_clip" to "क्लिपबोर्डबाट पढ्नुहोस्",
            "import_files" to "फाइलहरू आयात गर्नुहोस् (TXT, PDF, EPUB)",
            "devices_storage" to "यन्त्र भण्डारण र एसडी कार्ड स्क्यान",
            "search_desc" to "पुस्तकहरू, नोटहरू, फाइलहरू भित्र खोज्नुहोस्...",
            "audiobook" to "अडियोबुक थिएटर",
            "reading_active" to "पढाइ सक्रिय छ",
            "play_speech" to "आवाज बजाउनुहोस्",
            "sentence" to "वाक्य",
            "voice_style" to "आवाज शैली",
            "speed" to "गति थप",
            "pitch" to "पीच आवाज",
            "timer" to "स्लीप टाइमर",
            "hours" to "घण्टा",
            "minutes" to "मिनेट",
            "import_photo" to "कस्टम कभर फोटो",
            "photo_prompt" to "कभर थम्बनेल छवि URL टाँस्नुहोस्",
            "read_without_audio" to "आवाज बिना पढ्नुहोस् (सरल मोड)",
            "add_audio_later" to "तपाइँ आवाज प्लेब्याक बिना अफलाइन पढ्दै हुनुहुन्छ।",
            "enable_audio" to "अडियो प्लेब्याक पछि थप्नुहोस्",
            "validation_too_short" to "सामग्री खाली वा धेरै छोटो छ! कम्तिमा १५ अक्षर हुनुपर्छ।",
            "validation_title_empty" to "शीर्षक खाली हुन सक्दैन!",
            "scanned_title" to "स्क्यान गरिएका यन्त्र पुस्तकहरू",
            "choose_preset_cover" to "पेस्टल कभर डिजाइन छनौट गर्नुहोस्",
            "custom_ui_adjustments" to "इन्टरफेस शैलीहरू",
            "close" to "बन्द गर्नुहोस्",
            "play" to "बजाउनुहोस्",
            "pause" to "रोक्नुहोस्",
            "stop" to "रोक्नुहोस्",
            "previous" to "अघिल्लो",
            "next" to "अर्को",
            "text_preview" to "अक्षर पूर्वावलोकन आकार",
            "sim_file_alert" to "केवल पाठ लेआउट समर्थन गर्दछ!"
        ),
        Language.JAPANESE to mapOf(
            "app_title" to "ReaderMe",
            "library" to "ライブラリ",
            "player" to "プレイヤー",
            "stats" to "統計分析",
            "memos" to "メモ機能",
            "customise" to "テーマ設定",
            "settings" to "設定画面",
            "hamburger_menu" to "メニュー",
            "made_with_love" to "Editingcellsが愛を込めて制作 ♥",
            "import_safe" to "コンテンツを安全にインポート",
            "cancel" to "キャンセル",
            "save_read" to "保存して読む",
            "theme" to "テーマパレット",
            "dark_mode" to "ダークモード",
            "font_size" to "フォント比率",
            "select_lang" to "表示言語",
            "developer_credit" to "開発者クレジット",
            "no_books" to "該当する書籍が見つかりません。",
            "import_now" to "インポートする",
            "write_note" to "メモを新規作成 / テキスト入力",
            "read_clip" to "クリップボードから読込",
            "import_files" to "ファイルから読込 (TXT, PDF, EPUB)",
            "devices_storage" to "端末ストレージ＆SDカード読込",
            "search_desc" to "書籍、メモ、ファイル内を検索...",
            "audiobook" to "オーディオブックシアター",
            "reading_active" to "読書モード稼働中",
            "play_speech" to "音声再生",
            "sentence" to "文章",
            "voice_style" to "音声スタイル",
            "speed" to "話速速度",
            "pitch" to "ピッチ調節",
            "timer" to "スリープタイマー",
            "hours" to "時間",
            "minutes" to "分",
            "import_photo" to "カスタムカバー写真",
            "photo_prompt" to "サムネイル画像のURLを貼り付けてください",
            "read_without_audio" to "音声なしで読む (シンプル読書)",
            "add_audio_later" to "音声再生なしのオフライン読書モードです。",
            "enable_audio" to "あとから音声再生を有効にする",
            "validation_too_short" to "コンテンツが短すぎます！15文字以上入力してください。",
            "validation_title_empty" to "タイトルは必須です！",
            "scanned_title" to "スキャンされたデバイス書籍",
            "choose_preset_cover" to "パステルカバーデザイン選択",
            "custom_ui_adjustments" to "インターフェース調整",
            "close" to "閉じる",
            "play" to "再生",
            "pause" to "一時停止",
            "stop" to "停止",
            "previous" to "戻る",
            "next" to "進む",
            "text_preview" to "表示フォントサイズプレビュー",
            "sim_file_alert" to "テキストレイアウトの文書のみがサポートされています！"
        ),
        Language.SPANISH to mapOf(
            "app_title" to "ReaderMe",
            "library" to "Biblioteca",
            "player" to "Reproductor",
            "stats" to "Estadísticas",
            "memos" to "Memos",
            "customise" to "Personalizar Tema",
            "settings" to "Ajustes",
            "hamburger_menu" to "Menú",
            "made_with_love" to "Creado con ♥ por Editingcells",
            "import_safe" to "Importar contenido seguro",
            "cancel" to "Cancelar",
            "save_read" to "Guardar y Leer",
            "theme" to "Paleta de Colores",
            "dark_mode" to "Modo Oscuro",
            "font_size" to "Tamaño de fuente",
            "select_lang" to "Idiomas del App",
            "developer_credit" to "Créditos del Desarrollador",
            "no_books" to "Ningún libro coincide con la búsqueda.",
            "import_now" to "Importar ahora",
            "write_note" to "Escribir nota / Texto libre",
            "read_clip" to "Leer del Portapapeles",
            "import_files" to "Importar Documento (TXT, PDF, EPUB)",
            "devices_storage" to "Almacenamiento Local y Tarjeta SD",
            "search_desc" to "Buscar en libros, notas, archivos offline...",
            "audiobook" to "Teatro de Audiolibros",
            "reading_active" to "Lectura Activa",
            "play_speech" to "Reproducir Voz",
            "sentence" to "Frase",
            "voice_style" to "Voz Preset",
            "speed" to "Velocidad de Voz",
            "pitch" to "Tono de Voz",
            "timer" to "Temporizador",
            "hours" to "horas",
            "minutes" to "minutos",
            "import_photo" to "Portada Personalizada",
            "photo_prompt" to "Pegue la URL de la portada de imagen",
            "read_without_audio" to "Leer sin audio (Modo Simple)",
            "add_audio_later" to "Está leyendo sin reproducción de voz activa.",
            "enable_audio" to "Habilitar reproducción de audio más tarde",
            "validation_too_short" to "¡Contenido muy corto! Debe tener al menos 15 caracteres.",
            "validation_title_empty" to "¡El título no puede estar vacío!",
            "scanned_title" to "Libros locales escaneados",
            "choose_preset_cover" to "Seleccionar portada pastel",
            "custom_ui_adjustments" to "Estilos de Interfaz",
            "close" to "Cerrar",
            "play" to "Play",
            "pause" to "Pausar",
            "stop" to "Parar",
            "previous" to "Anterior",
            "next" to "Siguiente",
            "text_preview" to "Previsualización tipográfica",
            "sim_file_alert" to "¡Solo se admiten documentos con formato de texto!"
        )
    )

    fun getString(key: String, lang: Language): String {
        return translations[lang]?.get(key) ?: translations[Language.ENGLISH]?.get(key) ?: key
    }
}
